name: CICD

on:
  push:
    branches: [ main ]

jobs:
  run_migration_test:
    name: Run Flyway migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run database migrations
        run: ./migration.sh
        env:
          RDS_URL: ${{ secrets.RDS_URL }}
          RDS_USER: ${{ secrets.RDS_USER }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
