name: CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run_migration_test:
    name: Run Flyway migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install flyway
        run: wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/8.0.0/flyway-commandline-8.0.0-linux-x64.tar.gz | tar xz && sudo ln -s `pwd`/flyway-8.0.0/flyway /usr/local/bin
      - name: Run validation
        run: ./test.sh
      - name: Run database migrations
        if: github.event_name == 'push'
        run: flyway migrate
        env:
          FLYWAY_URL: jdbc:postgresql://${{ secrets.RDS_URL }}
          FLYWAY_USER: ${{ secrets.RDS_USER }}
          FLYWAY_PASSWORD: ${{ secrets.RDS_PASSWORD }}
