name: CICD

on:
  push:
    branches: [ main ]

jobs:
  run_migration_test:
    name: Run Flyway migrations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run database migrations
        run: ./migration.sh
